/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdReadinessRouteImport } from './routes/prod-readiness'
import { Route as ProdRouteImport } from './routes/prod'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as ApiAccountingStatusRouteImport } from './routes/api/accounting/status'
import { Route as AppReportIdRouteImport } from './routes/_app.report.$id'
import { Route as AppInspectionIdRouteImport } from './routes/_app.inspection.$id'
import { Route as AppExtractedIdRouteImport } from './routes/_app.extracted.$id'
import { Route as AppAnalysisIdRouteImport } from './routes/_app.analysis.$id'
import { Route as ApiAccountingSyncProviderRouteImport } from './routes/api/accounting/sync.$provider'
import { Route as ApiAccountingDisconnectProviderRouteImport } from './routes/api/accounting/disconnect.$provider'
import { Route as ApiAccountingConnectProviderRouteImport } from './routes/api/accounting/connect.$provider'
import { Route as ApiAccountingCallbackProviderRouteImport } from './routes/api/accounting/callback.$provider'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdReadinessRoute = ProdReadinessRouteImport.update({
  id: '/prod-readiness',
  path: '/prod-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdRoute = ProdRouteImport.update({
  id: '/prod',
  path: '/prod',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const ApiAccountingStatusRoute = ApiAccountingStatusRouteImport.update({
  id: '/api/accounting/status',
  path: '/api/accounting/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportIdRoute = AppReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionIdRoute = AppInspectionIdRouteImport.update({
  id: '/inspection/$id',
  path: '/inspection/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExtractedIdRoute = AppExtractedIdRouteImport.update({
  id: '/extracted/$id',
  path: '/extracted/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisIdRoute = AppAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAccountingSyncProviderRoute =
  ApiAccountingSyncProviderRouteImport.update({
    id: '/api/accounting/sync/$provider',
    path: '/api/accounting/sync/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountingDisconnectProviderRoute =
  ApiAccountingDisconnectProviderRouteImport.update({
    id: '/api/accounting/disconnect/$provider',
    path: '/api/accounting/disconnect/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountingConnectProviderRoute =
  ApiAccountingConnectProviderRouteImport.update({
    id: '/api/accounting/connect/$provider',
    path: '/api/accounting/connect/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountingCallbackProviderRoute =
  ApiAccountingCallbackProviderRouteImport.update({
    id: '/api/accounting/callback/$provider',
    path: '/api/accounting/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prod': typeof ProdRoute
  '/prod-readiness': typeof ProdReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/report': typeof ApiReportRoute
  '/analysis/$id': typeof AppAnalysisIdRoute
  '/extracted/$id': typeof AppExtractedIdRoute
  '/inspection/$id': typeof AppInspectionIdRoute
  '/report/$id': typeof AppReportIdRoute
  '/api/accounting/status': typeof ApiAccountingStatusRoute
  '/api/accounting/callback/$provider': typeof ApiAccountingCallbackProviderRoute
  '/api/accounting/connect/$provider': typeof ApiAccountingConnectProviderRoute
  '/api/accounting/disconnect/$provider': typeof ApiAccountingDisconnectProviderRoute
  '/api/accounting/sync/$provider': typeof ApiAccountingSyncProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prod': typeof ProdRoute
  '/prod-readiness': typeof ProdReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/report': typeof ApiReportRoute
  '/analysis/$id': typeof AppAnalysisIdRoute
  '/extracted/$id': typeof AppExtractedIdRoute
  '/inspection/$id': typeof AppInspectionIdRoute
  '/report/$id': typeof AppReportIdRoute
  '/api/accounting/status': typeof ApiAccountingStatusRoute
  '/api/accounting/callback/$provider': typeof ApiAccountingCallbackProviderRoute
  '/api/accounting/connect/$provider': typeof ApiAccountingConnectProviderRoute
  '/api/accounting/disconnect/$provider': typeof ApiAccountingDisconnectProviderRoute
  '/api/accounting/sync/$provider': typeof ApiAccountingSyncProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/prod': typeof ProdRoute
  '/prod-readiness': typeof ProdReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upload': typeof AppUploadRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/report': typeof ApiReportRoute
  '/_app/analysis/$id': typeof AppAnalysisIdRoute
  '/_app/extracted/$id': typeof AppExtractedIdRoute
  '/_app/inspection/$id': typeof AppInspectionIdRoute
  '/_app/report/$id': typeof AppReportIdRoute
  '/api/accounting/status': typeof ApiAccountingStatusRoute
  '/api/accounting/callback/$provider': typeof ApiAccountingCallbackProviderRoute
  '/api/accounting/connect/$provider': typeof ApiAccountingConnectProviderRoute
  '/api/accounting/disconnect/$provider': typeof ApiAccountingDisconnectProviderRoute
  '/api/accounting/sync/$provider': typeof ApiAccountingSyncProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/prod'
    | '/prod-readiness'
    | '/reset-password'
    | '/terms-of-service'
    | '/alerts'
    | '/dashboard'
    | '/settings'
    | '/upload'
    | '/api/alerts'
    | '/api/analyze'
    | '/api/extract'
    | '/api/report'
    | '/analysis/$id'
    | '/extracted/$id'
    | '/inspection/$id'
    | '/report/$id'
    | '/api/accounting/status'
    | '/api/accounting/callback/$provider'
    | '/api/accounting/connect/$provider'
    | '/api/accounting/disconnect/$provider'
    | '/api/accounting/sync/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/prod'
    | '/prod-readiness'
    | '/reset-password'
    | '/terms-of-service'
    | '/alerts'
    | '/dashboard'
    | '/settings'
    | '/upload'
    | '/api/alerts'
    | '/api/analyze'
    | '/api/extract'
    | '/api/report'
    | '/analysis/$id'
    | '/extracted/$id'
    | '/inspection/$id'
    | '/report/$id'
    | '/api/accounting/status'
    | '/api/accounting/callback/$provider'
    | '/api/accounting/connect/$provider'
    | '/api/accounting/disconnect/$provider'
    | '/api/accounting/sync/$provider'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/prod'
    | '/prod-readiness'
    | '/reset-password'
    | '/terms-of-service'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/upload'
    | '/api/alerts'
    | '/api/analyze'
    | '/api/extract'
    | '/api/report'
    | '/_app/analysis/$id'
    | '/_app/extracted/$id'
    | '/_app/inspection/$id'
    | '/_app/report/$id'
    | '/api/accounting/status'
    | '/api/accounting/callback/$provider'
    | '/api/accounting/connect/$provider'
    | '/api/accounting/disconnect/$provider'
    | '/api/accounting/sync/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProdRoute: typeof ProdRoute
  ProdReadinessRoute: typeof ProdReadinessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiAccountingStatusRoute: typeof ApiAccountingStatusRoute
  ApiAccountingCallbackProviderRoute: typeof ApiAccountingCallbackProviderRoute
  ApiAccountingConnectProviderRoute: typeof ApiAccountingConnectProviderRoute
  ApiAccountingDisconnectProviderRoute: typeof ApiAccountingDisconnectProviderRoute
  ApiAccountingSyncProviderRoute: typeof ApiAccountingSyncProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prod-readiness': {
      id: '/prod-readiness'
      path: '/prod-readiness'
      fullPath: '/prod-readiness'
      preLoaderRoute: typeof ProdReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prod': {
      id: '/prod'
      path: '/prod'
      fullPath: '/prod'
      preLoaderRoute: typeof ProdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/accounting/status': {
      id: '/api/accounting/status'
      path: '/api/accounting/status'
      fullPath: '/api/accounting/status'
      preLoaderRoute: typeof ApiAccountingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/report/$id': {
      id: '/_app/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AppReportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspection/$id': {
      id: '/_app/inspection/$id'
      path: '/inspection/$id'
      fullPath: '/inspection/$id'
      preLoaderRoute: typeof AppInspectionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extracted/$id': {
      id: '/_app/extracted/$id'
      path: '/extracted/$id'
      fullPath: '/extracted/$id'
      preLoaderRoute: typeof AppExtractedIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analysis/$id': {
      id: '/_app/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AppAnalysisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/accounting/sync/$provider': {
      id: '/api/accounting/sync/$provider'
      path: '/api/accounting/sync/$provider'
      fullPath: '/api/accounting/sync/$provider'
      preLoaderRoute: typeof ApiAccountingSyncProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounting/disconnect/$provider': {
      id: '/api/accounting/disconnect/$provider'
      path: '/api/accounting/disconnect/$provider'
      fullPath: '/api/accounting/disconnect/$provider'
      preLoaderRoute: typeof ApiAccountingDisconnectProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounting/connect/$provider': {
      id: '/api/accounting/connect/$provider'
      path: '/api/accounting/connect/$provider'
      fullPath: '/api/accounting/connect/$provider'
      preLoaderRoute: typeof ApiAccountingConnectProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounting/callback/$provider': {
      id: '/api/accounting/callback/$provider'
      path: '/api/accounting/callback/$provider'
      fullPath: '/api/accounting/callback/$provider'
      preLoaderRoute: typeof ApiAccountingCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppAnalysisIdRoute: typeof AppAnalysisIdRoute
  AppExtractedIdRoute: typeof AppExtractedIdRoute
  AppInspectionIdRoute: typeof AppInspectionIdRoute
  AppReportIdRoute: typeof AppReportIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppAnalysisIdRoute: AppAnalysisIdRoute,
  AppExtractedIdRoute: AppExtractedIdRoute,
  AppInspectionIdRoute: AppInspectionIdRoute,
  AppReportIdRoute: AppReportIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProdRoute: ProdRoute,
  ProdReadinessRoute: ProdReadinessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiReportRoute: ApiReportRoute,
  ApiAccountingStatusRoute: ApiAccountingStatusRoute,
  ApiAccountingCallbackProviderRoute: ApiAccountingCallbackProviderRoute,
  ApiAccountingConnectProviderRoute: ApiAccountingConnectProviderRoute,
  ApiAccountingDisconnectProviderRoute: ApiAccountingDisconnectProviderRoute,
  ApiAccountingSyncProviderRoute: ApiAccountingSyncProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
